vsync = true
maximized = false
srgb = true
idle = false
no-multigrid = true
frame = "full"

[font]
size = 16
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "Maple Mono"
style = "Light"

[[font.bold]]
family = "Maple Mono"
style = "Medium"

[[font.italic]]
family = "Maple Mono"
style = "Light Italic"

[[font.bold_italic]]
family = "Maple Mono"
style = "Medium Italic"

[font.features]
"JetBrainsMono Nerd Font" = [
  "+calt",
  "+ss20",
  "+cv02",
  "+ss02",
  "+cv14",
  "+cv18",
  "+cv20",
]
